### ISSUE TITLE
Offline viewing

### ISSUE THREAD

**Issue by Ansh4011** [Hanziness/AnotherPomodoro#347]
**Is your feature request related to a problem? Please describe.**
How may I view the website offline? That's a vital feature imho, I can then access the website anywhere and anytime. Can also install the web app from browser and use it as a separate app then.

**Describe the solution you'd like**
I'm not a developer, but ig it's related to caching the website or something similar. 

**Additional context**
Maybe check [Monkeytype's](https://github.com/monkeytypegame/monkeytype) source code for reference if needed, they have complete offline functionality.

**Comment by Hanziness** [comment]
Hi! Sorry for the very late response. *In theory* there is a service worker that performs caching on first launch so that the app is available offline after that. I'll investigate if it works properly, especially if network conditions are set to fully offline. Similarly the app can be installed from the browser. In Google Chrome, look for the install icon at the right side of the address bar.

**Comment by Ansh4011** [comment]
Hi, yes I have tried all that stuff, doesn't seem to work whatsoever. It
simply says *You're Offline*.
